// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPkWZ7aZZpY5JPgx6NFs51HZ-g6O_WkSU',
    appId: '1:1052409059860:web:0c3e747fae38fc4aba6501',
    messagingSenderId: '1052409059860',
    projectId: 'grocery-app-d9595',
    authDomain: 'grocery-app-d9595.firebaseapp.com',
    storageBucket: 'grocery-app-d9595.appspot.com',
    measurementId: 'G-6P80XGNJKS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs-W2iQvLkbHGAuXmUbJuxGSG-05hpLtw',
    appId: '1:1052409059860:android:3d4c689e6b27e93eba6501',
    messagingSenderId: '1052409059860',
    projectId: 'grocery-app-d9595',
    storageBucket: 'grocery-app-d9595.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-N-LoPzzC4DIiaN8rAUEO2HUBj4dBBJo',
    appId: '1:1052409059860:ios:48cc08b36bf74ec1ba6501',
    messagingSenderId: '1052409059860',
    projectId: 'grocery-app-d9595',
    storageBucket: 'grocery-app-d9595.appspot.com',
    iosBundleId: 'com.techedu.groceryUserApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-N-LoPzzC4DIiaN8rAUEO2HUBj4dBBJo',
    appId: '1:1052409059860:ios:48cc08b36bf74ec1ba6501',
    messagingSenderId: '1052409059860',
    projectId: 'grocery-app-d9595',
    storageBucket: 'grocery-app-d9595.appspot.com',
    iosBundleId: 'com.techedu.groceryUserApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPkWZ7aZZpY5JPgx6NFs51HZ-g6O_WkSU',
    appId: '1:1052409059860:web:f48654d6ea1c3045ba6501',
    messagingSenderId: '1052409059860',
    projectId: 'grocery-app-d9595',
    authDomain: 'grocery-app-d9595.firebaseapp.com',
    storageBucket: 'grocery-app-d9595.appspot.com',
    measurementId: 'G-RE9YQ08V3J',
  );
}
